services:
  - type: web
    name: ctv-chatgpt-grok-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: API_BASE
        value: http://103.69.87.202:5000
      - key: API_KEY
        sync: false
      - key: API_KEY2
        sync: false
